#!/usr/bin/perl

use strict;
use warnings;

my $DEBUG = 0;

open OUT, ">writings.tex" or die "Failed to open OUT: $!\n";

print OUT "% DO NOT EDIT THIS FILE. IT IS AUTO-GENERATED FROM generate-tex.pl. RUN `make`.\n";
print OUT "\\documentclass[11pt]{article}\n";
print OUT "\\usepackage[top=1in,bottom=1.25in,left=1.55in,right=1.55in]{geometry}\n\n";
print OUT "\\usepackage{pdfpages}\n";
print OUT "\\usepackage{fontspec}\n";
print OUT "\\setmainfont[BoldFont={HoeflerText-Bold},ItalicFont={Hoefler Text Italic},BoldItalicFont={Hoefler Text Black Italic},SmallCapsFont={HoeflerText-RomanSC},Ligatures={NoCommon, TeX}]{Hoefler Text}\n";
print OUT "\\setmonofont[Ligatures={TeX}]{Source Code Pro Medium}\n\n";
print OUT "\\usepackage{setspace}\n";
print OUT "\\setstretch{1.15}\n";
print OUT "\\setlength{\\parindent}{14.25pt}\n\n";
print OUT "\\begin{document}\n";

# Run through each of the episodes. Count the number of words in each file. Print that number plus the contents of the file.
opendir EPISODES, "." or die "Cannot open EPISODES: $!\n";
my @files = sort readdir(EPISODES);
my $current_file = "";
my $word_count = 0;
my $unix_word_count = 0;
my $total_word_count = 0;

while ( $current_file = shift @files )
{
    next if ( $current_file =~ /^\./ or $current_file !~ /^2014-/ );
    print "Current file: " . $current_file . "\n" if $DEBUG;
    
    my $sentence_length = sentence_length($current_file);
    
    if ( $current_file =~ /^2014-[0-9]{2}-[0-9]{2}-a.tex$/ )
    {
        # Bold the text in these files.
        $word_count = 0;
        $unix_word_count = `wc -w $current_file`;
        $word_count = substr($unix_word_count,0,3);
        $word_count =~ s/\s+$//;
        print "Word count: $unix_word_count\n" if $DEBUG;
        print OUT "\\textbf{" . substr($current_file,0,-6) . "}\n\n";
        print OUT "\\textbf{\\input{$current_file}}\n\n";
        next;
    }
    elsif ( $current_file =~ /^2014-[0-9]{2}-[0-9]{2}.tex$/ )
    {
        # Print the word count (bolded) and then the episode.
        $unix_word_count = `wc -w $current_file`;
        print "Word count: $unix_word_count\n" if $DEBUG;
        $word_count += substr($unix_word_count,0,3);
        print "$word_count\n";
        $total_word_count += $word_count;
        print OUT "\\textbf{Word count: " . substr($word_count,0,3) . "}\n\n";
        print OUT "\\textbf{Average sentence length: " . $sentence_length . "}\n\n~\n\n";
        print OUT "\\input{$current_file}\n\n~\n\n";
        # print OUT "\\clearpage\n\n";
    }
}

closedir EPISODES;

print OUT "Total word count: $total_word_count" if $DEBUG;

print OUT "\\end{document}\n";

close OUT;

sub sentence_length
{
    my $file = shift;
    open FILE, "<$file" or die "Failed to open FILE: $!\n";
    
    my $total_sentences = 0;
    my $total_words = 0;
    my $average_sentence_length = 0;
    
    while( my $line = <FILE> )
    {
        my @words = split(" ",$line);
        my $number_of_words = @words;
        $total_words = $total_words+$number_of_words;
    }
    
    close(FILE);
    open FILE2, "<$file" or die "Cannot open FILE2: $!\n";
    
    while( my $ch = getc(FILE2) )
    {
        if( $ch eq "." or $ch eq "!" or $ch eq "?" )
        {
            $total_sentences++;
        }
    }
    
    $average_sentence_length = $total_words/$total_sentences;
    $average_sentence_length = sprintf("%.1f", $average_sentence_length); # Round
    return $average_sentence_length;
}
